// Auto generated by `gen_record_extensions.dart`. Do not modify!
part of 'record_extensions.dart';
extension RecordOf3ParsersExt<T0, T1, T2> on (p.Parser<T0>, p.Parser<T1>, p.Parser<T2>) {
	p.Parser<(T0, T1, T2)> toParser() => p.list([$1, $2, $3]).mapOk((v) => (v[0] as T0, v[1] as T1, v[2] as T2));}

extension E3ParsersExt<T0, T1, T2> on p.Parser<(T0, T1, T2)> {
	p.Parser<T2> get onlyLast => mapOk((v) => v.$3);
	p.Parser<T0> get onlyFirst => mapOk((v) => v.$1);
}
