// Auto generated by `gen_record_extensions.dart`. Do not modify!
import 'package:potatoparser/potatoparser.dart' as p;
part 'ext2.dart';
part 'ext3.dart';
part 'ext4.dart';
part 'ext5.dart';
part 'ext6.dart';
part 'ext7.dart';
part 'ext8.dart';
part 'ext9.dart';
part 'ext10.dart';
part 'ext11.dart';
part 'ext12.dart';
part 'ext13.dart';
part 'ext14.dart';
part 'ext15.dart';
